### ISSUE TITLE
Cambiar setup de REDIS-HOST en Rakefile.

### ISSUE THREAD

**Issue by alvaro-gh** [Shelvak/firehouse_audio#1]
En el Rakefile el REDIS-HOST se setea con el formato de las ENV que genera Docker. Podés cambiar eso para que se setee con una ENV REDIS-HOST y después en el deploy igualarla a la ENV que genera Docker?
Para que sea más flexible.

**Comment by Shelvak** [comment]
Ahí está `REDIS_HOST` le tenes que mandar :+1:
