### ISSUE TITLE
Inicializar log files.

### ISSUE THREAD

**Issue by alvaro-gh** [Shelvak/firehouse_audio#2]
La aplicación loggea por stdout cuando inicia pero no avisa nada en sus logs. Estaría bueno inicializar ambos logs para verlos desde log.io en nuestro caso.

**Comment by Shelvak** [comment]
Lo que sale por el stdout son "prints" informativos, los logs los manda al `/logs/audioplayer.log|error` sino le podes pasar una variable `logs_path` que si te pinta se la cambiamos, por defecto sale todo por el logs.

**Comment by alvaro-gh** [comment]
En realidad quería una línea del estilo "Iniciando servicio" ponele, al final se la agregué a manopla. Lo utilicé solamente para debuggear, ya no sería necesario.
